### ISSUE TITLE
Cannot see translation on my language

### ISSUE THREAD

**Issue by aeleftheriadis** [andrew-sygyda/meteor-i18n-admin#6]
I have started a new project from https://github.com/yogiben/meteor-starter
then removed yogiben:admin and added your package. Then I have added my el.i18n.json with all the translations on i18n folder and then changed the admin language and also the default language to el. I cannot see greek language on admin (admin remain in english), only on dashboard and home. I have also tried to change the language to ru but admin is always on english language. Any help appreciated.

**Comment by andrew-sygyda** [comment]
Hi @aeleftheriadis! I think localization of https://github.com/yogiben/meteor-starter is only for user side not admin. 
In this repository was translated only 'ru' and 'zh-CN'.
I think you can clone this repository to your project /package directory and add  el.i18n.json to package/ansyg:i18n-admin/i18n

**Comment by aeleftheriadis** [comment]
I will try this solution to clone your package to the package folder and report back.
Thanks @andrew-sygyda.
