### ISSUE TITLE
cant see All Posts/Comments/Users 

### ISSUE THREAD

**Issue by YYwork** [andrew-sygyda/meteor-i18n-admin#7]

**Comment by andrew-sygyda** [comment]
Can you show your .meteor/packages files and config options?
And did you create *.i18n.json somewhere in common folder?

**Comment by YYwork** [comment]
<img width="1229" alt="a57558cd-9644-4956-a52c-13540686c942" src="https://cloud.githubusercontent.com/assets/13248020/10183576/c9f2b766-6763-11e5-8c9b-2d6353fc945f.png">
there is nothing here

**Comment by YYwork** [comment]
I have one post  
<img width="1004" alt="1" src="https://cloud.githubusercontent.com/assets/13248020/10183610/4b0c92ae-6764-11e5-8336-1d82375b9f86.png">
but there is nothing 
<img width="1218" alt="2" src="https://cloud.githubusercontent.com/assets/13248020/10183618/5bba7760-6764-11e5-9e1c-87768a32fc19.png">
